version: 2
jobs:
  build:
    parallelism: 4
    docker:
    - image: circleci/node:10.5.0
    working_directory: ~/repo
    steps:
    - checkout
    - run: npm install
    - run: npm run lintfix
    - run: npm run build
    - run: npm run test
