version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.5.0
    working_directory: ~/repo
    steps:
    - checkout
    - run: npm install
    - run: yarn install
    - run: yarn build-dlls
    - run: yarn build
    - run: yarn lint
    - run: yarn test
workflows:
  version: 2
  workflow:
    jobs:
    - build
